jobs:
  include:
    - stage: Windows build
      os: windows
      language: go
      go: "1.13"
      script:
        - go test -v ./tests/...
      before_deploy:
        - powershell -executionpolicy bypass -command "scripts/windows.ps1 -TravisOS ${TRAVIS_OS_NAME} -TravisArch ${TRAVIS_CPU_ARCH} -TravisTag ${TRAVIS_TAG}"
      deploy:
        provider: releases
        file_glob: true
        file: dist/*
        draft: true
        cleanup: false
        token:
          secure: vZRv6LzYWbKf66xR9fiGtc5SdvGw8SnmIBiNe1d1xGmd73zc94edFaPl3DIDozo19ityqXbHWX5X6ulJcOAWZpynHwTiI/w6d5/1zqb5oBmWs65TqxGw9r6w8a8mFf2olSo054ztjW5RF7mRAnExVVI5CjNcqkARoL+J1bSOu3BQkoj0tzTRvKB2j4LzM9zEMaaQgmUmsiOkvtaIwYxKZo8E7hkmwH4J7lJmBXixmNiovbtek4zTpiyjOC8GYNim2vRTxxiBVl33nfntHpUsrelviF8bFaKgTlwm9RURYt+clfrsaC5R14PoagXBiUzSr1qMIiC0TdRLuWyzD0jlNXdmOL6Ms0V4ADJSUQcR/0Dm/VpJVYCsitvx5dpP8Voinjtif/PcW3fdRg4BXza9INCFKI/+VJq7tvuFswyuiTWX4h7QgKicRaEj9L+nIV2+cvaHgQ0fcRCqKbeOemJA2Qwnfsy9V5xEZVriyLuhQS9LuA3Pgug8VtA3+ekpS+FVuY752Z2GqoRzXHOZg4ijtOdyfResxzPNYV547r+LyuFmJZwTvICoxGGmlXhTQan+LmlgAx8N92eCvMMMqNE/30UjaxzN4sARpEJf9MEAAFztkwrnohYElKtKcSlO/exyQyEt0LaWSQsWunRX0C75VgonGnk1PzLjegj7XiaL5xY=
        on:
          tags: true
    - stage: OSX build
      os: osx
      language: go
      go: "1.13"
      script:
        - go test -v ./tests/...
      before_deploy:
        - bash scripts/osx.sh
      deploy:
        provider: releases
        file_glob: true
        file: dist/*
        draft: false
        cleanup: false
        release_notes_file: RELEASE.md
        token:
          secure: vZRv6LzYWbKf66xR9fiGtc5SdvGw8SnmIBiNe1d1xGmd73zc94edFaPl3DIDozo19ityqXbHWX5X6ulJcOAWZpynHwTiI/w6d5/1zqb5oBmWs65TqxGw9r6w8a8mFf2olSo054ztjW5RF7mRAnExVVI5CjNcqkARoL+J1bSOu3BQkoj0tzTRvKB2j4LzM9zEMaaQgmUmsiOkvtaIwYxKZo8E7hkmwH4J7lJmBXixmNiovbtek4zTpiyjOC8GYNim2vRTxxiBVl33nfntHpUsrelviF8bFaKgTlwm9RURYt+clfrsaC5R14PoagXBiUzSr1qMIiC0TdRLuWyzD0jlNXdmOL6Ms0V4ADJSUQcR/0Dm/VpJVYCsitvx5dpP8Voinjtif/PcW3fdRg4BXza9INCFKI/+VJq7tvuFswyuiTWX4h7QgKicRaEj9L+nIV2+cvaHgQ0fcRCqKbeOemJA2Qwnfsy9V5xEZVriyLuhQS9LuA3Pgug8VtA3+ekpS+FVuY752Z2GqoRzXHOZg4ijtOdyfResxzPNYV547r+LyuFmJZwTvICoxGGmlXhTQan+LmlgAx8N92eCvMMMqNE/30UjaxzN4sARpEJf9MEAAFztkwrnohYElKtKcSlO/exyQyEt0LaWSQsWunRX0C75VgonGnk1PzLjegj7XiaL5xY=
        on:
          tags: true
