jobs:
  include:
  - stage: Windows build
    os: windows
    language: go
    go: '1.13'
    script:
    - go test -v ./tests/...
    before_deploy:
    - powershell -executionpolicy bypass -command "scripts/windows.ps1 -TravisOS ${TRAVIS_OS_NAME}
      -TravisArch ${TRAVIS_CPU_ARCH} -TravisTag ${TRAVIS_TAG}"
    deploy:
      provider: releases
      file_glob: true
      file: dist/*
      draft: true
      cleanup: false
      token:
        secure: fXnAAlr7G45UzoS5ELOKxMFrGi1D8jzqx9AEkzztO8bmEfl/CTNR5Q//+8IcEgMyYUpSSYH9VpPmxutzzPUyLgEDG69hFlRBZTcTU/5Dmdz1NYTA805Ybduk/l6xpJdxpEQfyJFga7tO+GaOglmaY3/lOyf0Llui+SEcu9Kl4xEFGMMs0Hvet9rz1GMLSniytD252y/npKv4c1VpxXGDEflUx1Vr99d7nlnnjguyRzeCq50/5cDND4ur5CVPv8V/jM3i4y+gtTkgpBaArwi11wdLEkCsyek/92gB7xskgfN7tue7aliuFZLQelxbTd6JDs6Q7SqiAcfEKKwH/azpxNTRNPckRP5oYDldeFK9OciRzT9w5EHGVfXkuZtL6uDD43JrnoZCJoaJZJ2oQDMNenjngeqpFxJpz6UvqGhsVGJF08xKcrsm+ZhMZG3/Eb+AEl7T9Nsqw/JBu1izwA8WGz5xvclBsCVTF1GWeeOaQYIs7tviQwqzn/C6vMV8gz99JXkdwjzoIHmSvKr2vI9AdigX9ZK+9qkqSa+paOZicNBFgdCSvRMJSto49ShgKDFGKoXi1b7+eTzZXeniEgSHnyqtpSfRxmviBr+78ae1lrXdx7m5s1umvpvIzAOrAzfkqkfM0gqipz3KXrBgO4v4BS/leh5NR8xFKeZQmmM790w=
      on:
        tags: true
  - stage: OSX build
    os: osx
    language: go
    go: '1.13'
    script:
    - go test -v ./tests/...
    before_deploy:
    - bash scripts/osx.sh
    deploy:
      provider: releases
      file_glob: true
      file: dist/*
      draft: false
      cleanup: false
      release_notes_file: RELEASE.md
      token:
        secure: fXnAAlr7G45UzoS5ELOKxMFrGi1D8jzqx9AEkzztO8bmEfl/CTNR5Q//+8IcEgMyYUpSSYH9VpPmxutzzPUyLgEDG69hFlRBZTcTU/5Dmdz1NYTA805Ybduk/l6xpJdxpEQfyJFga7tO+GaOglmaY3/lOyf0Llui+SEcu9Kl4xEFGMMs0Hvet9rz1GMLSniytD252y/npKv4c1VpxXGDEflUx1Vr99d7nlnnjguyRzeCq50/5cDND4ur5CVPv8V/jM3i4y+gtTkgpBaArwi11wdLEkCsyek/92gB7xskgfN7tue7aliuFZLQelxbTd6JDs6Q7SqiAcfEKKwH/azpxNTRNPckRP5oYDldeFK9OciRzT9w5EHGVfXkuZtL6uDD43JrnoZCJoaJZJ2oQDMNenjngeqpFxJpz6UvqGhsVGJF08xKcrsm+ZhMZG3/Eb+AEl7T9Nsqw/JBu1izwA8WGz5xvclBsCVTF1GWeeOaQYIs7tviQwqzn/C6vMV8gz99JXkdwjzoIHmSvKr2vI9AdigX9ZK+9qkqSa+paOZicNBFgdCSvRMJSto49ShgKDFGKoXi1b7+eTzZXeniEgSHnyqtpSfRxmviBr+78ae1lrXdx7m5s1umvpvIzAOrAzfkqkfM0gqipz3KXrBgO4v4BS/leh5NR8xFKeZQmmM790w=
      on:
        tags: true